### PR TITLE
#393 #394 Category and tag list layout

### PR DESCRIPTION
**Pull request by gvdp**
Proposal to address issues #393 and #394. Made the lists a bit nicer and added a background and font-awesome icons. I made a separate `.scss` file, maybe that's not necessary. 

Not really sure about the colors but I tried some and this looks ok to me. Better designers probably have better ideas for this. Should probably use some from the sass variables but they didn't look nice to me. 
Also, used old font awesome icons because the site still uses an old version (4.3.0 i/o 5.3)

Preview of the layout:

image

### CODE REVIEW

**Comment by gurtjun** [comment]
Looks very nice, @gvdp, great job!

Regarding the categories: I think we can "merge" some... 
For example: 
- `JOIN-event`, `Devoxx` and `JAX London` are actually all `Conferences`
- `AngularJS-Typescript` posts are actually about `Angular`
- ...

Same for the tags, they look more like SEO keywords to me. Maybe we could add a new frontmatter tag (`seo`) with those keywords and add them to `<meta name="keywords"/>`? And set a limit on the tags per blog post?

**Comment by yannickdeturck** [comment]
Ohhh, I really like that styling. Much cleaner.
Nice work, @gvdp! 👍🏼

@gurtjun, I agree that we could merge (the Angular ones for example) and remove (Tech and other ones that don't say that much) some of the categories and tags.

Thoughts, @MrJean ?

**Comment by MrJean** [comment]
Nice update @Glennvdp ! 

Some suggestions:

* Make the animation on the hover faster, now it's very slow.
* When you click on a tag or categorie you end up on a new page and the categories/tags are not styled on these pages. Could you please check?

**Comment by gvdp** [comment]
Good catch, I didn't know there were lists on other pages as well.

Added the new styling to those and sped up the animation.

**Comment by yannickdeturck** [comment]
After a little bit of delay...
Thanks, @gvdp! Nice work! 👌🏼

**Pull request merged**
