### PR TITLE
Added the possibility to add a caption to an image

### PR DESCRIPTION
**Pull request by TYsewyn**
To add a caption to an image, you can use the following snippet:

`{% include image.html
            img="/location/of/image.jpg"
            class="center-block"
            alt="Alternative text"
            title="Image title"
            caption="Caption for the image" %}
`

### CODE REVIEW

**Comment by tomverelst** [comment]
Trying it out!

**Comment by tomverelst** [comment]
Would be great if we can add anchors to the image. Also, awaiting this feature, I used figures and figcaption tags. Example:

```
<div class="figures">
  <a href="{{ '/img/prometheus/grafana-datasource.jpg' | prepend: site.baseurl }}">
  <figure>
      <img style="max-width: 320px;" alt="Prometheus Datasource" src="{{ '/img/prometheus/grafana-datasource.jpg' | prepend: site.baseurl }}">
      <figcaption>Step 1: Create datasource</figcaption>
  </figure>
  </a>

  <a href="{{ '/img/prometheus/grafana-dashboard.jpg' | prepend: site.baseurl }}">
  <figure>
    <img style="max-width: 320px;" alt="Grafana Dashboard" src="{{ '/img/prometheus/grafana-dashboard.jpg' | prepend: site.baseurl }}">
    <figcaption>Step 2: Profit</figcaption>
  </figure>
  </a>
</div>
```

**Comment by TYsewyn** [comment]
I was also thinking of switching to the HTML5 tags `figure` and `figcaption` after I created the PR.
At first I added anchors, but then for some reason I deleted it. I'll add it back as an option :)

I'm not sure if I'll be able to pull off the multiple images though.

**Comment by TYsewyn** [comment]
To create a grid of multiple images, you should wrap the `include` tag in div containers, using the grid system of Bootstrap.

```
<div class="row">
  <div class="col-md-6">
    {% include image.html img="/img/prometheus/grafana-datasource.jpg" alt="Prometheus Datasource" title="Prometheus Datasource" caption="Step 1: Create datasource" link="{{ '/img/prometheus/grafana-datasource.jpg' | prepend: site.baseurl }}" %}
  </div>
  <div class="col-md-6">
    {% include image.html img="/img/prometheus/grafana-dashboard.jpg" alt="Grafana Dashboard" title="Grafana Dashboard" caption="Step 2: Profit" link="{{ '/img/prometheus/grafana-dashboard.jpg' | prepend: site.baseurl }}" %}
  </div>
</div>
```

**Pull request merged**
