### PR TITLE
Resize iframe on load (#334)

### PR DESCRIPTION
**Pull request by gurtjun**
Possible fix for the tech radar scaling, more testing required (multiple browsers)

### CODE REVIEW

**Comment by MrJean** [comment]
@gurtjun Did you take into account the code in main.js?

https://github.com/ordina-jworks/ordina-jworks.github.io/blob/1da9eec0a12bbd49c6e4f494ff8a4533d9061100/js/main.js#L112

**Comment by gurtjun** [comment]
@MrJean Yes I noticed that piece of code. You want to move the javascript part from `techradar.html` to `main.js`?

**Comment by MrJean** [comment]
@gurtjun Point being that you prolly don't need that piece of code anymore since you're scaling the iframe onload?

**Comment by gurtjun** [comment]
@MrJean I think we still need the dirty hack. I guess the height of the iframe cannot be changed until the content of the iframe is loaded. If you remove the hack, it does not work (on my machine).

**Pull request merged**
