### PR TITLE
Fix broken links (#325)

### PR DESCRIPTION
**Pull request by gurtjun**
@andreasevers Do you have a higher resolution picture of [you, Sergi and Josh](https://github.com/ordina-jworks/ordina-jworks.github.io/blob/fix/325/broken-links/img/SpringIO2015/sergi-andreas-josh.jpg)? 

@kencoenen The images in [your blogpost of JAX London](https://github.com/ordina-jworks/ordina-jworks.github.io/blob/fix/325/broken-links/_posts/2015-10-13-MicroservicesPatterns.md) are hidden since I'm not sure which ones to pick.

### CODE REVIEW

**Comment by andreasevers** [comment]
Found it!

**Comment by gurtjun** [comment]
Whoops, might be a good idea to shrink the image a bit... Current size is 2.1 MB. What do you guys think?

**Comment by yannickdeturck** [comment]
Yeah, definitely! Ideally resize it to the size in which it's displayed?

**Comment by yannickdeturck** [comment]
Perfect! Let's ship it. 👊🏼

**Pull request merged**
