### PR TITLE
Add inactive author badge (#431)

### PR DESCRIPTION
**Pull request by gurtjun**
I developed this using Chrome Devtools, can someone check if this proposal actually works? Was not able to run the blog locally on work PC.

### CODE REVIEW

**Comment by gurtjun** [comment]
Looks like this:

screenshot 2018-10-09 at 18 43 44


Should we disable the social icons? Any suggestions are welcome.

**Comment by gurtjun** [comment]
Or add strikethrough for titles?
image

**Comment by yannickdeturck** [comment]
Strikethrough is a bit too much imo. :)
The alumni badge looks nice.

**Comment by Turbots** [comment]
Agreed, badge is very nice, strikethrough is too much imo :D

**Comment by Turbots** [comment]
We should disable the social icons that are no longer relevant (if its an ordina email, disable it)

**Comment by TimDG** [comment]
Maak er `alumnus` van. `alumni` is meervoud.
Hoe ziet het er trouwens uit met de badge onder de foto?

**Comment by gurtjun** [comment]
Ok, strikethrough was added in a26f6a7. We should revert that one. 
Badge at the bottom required too much CSS refactoring @TimDG 😄

**Comment by yannickdeturck** [comment]
Ok, removed that commit!

**Comment by gurtjun** [comment]
Ok, done!

**Comment by yannickdeturck** [comment]
@gurtjun, do you think it's easy to hide the email button of an inactive author if it ends with "@ordina.be"?

**Comment by Turbots** [comment]
@yannickdeturck if you have to put someone in 'inactive' anyway, you can just remove his email at the same time, no? no need for complicated if/elses I guess

**Comment by yannickdeturck** [comment]
> @yannickdeturck if you have to put someone in 'inactive' anyway, you can just remove his email at the same time, no? no need for complicated if/elses I guess

Fair enough. 😄

**Comment by gurtjun** [comment]
Wait a moment @yannickdeturck, I have to do some CSS updates to make sure the badge is centered.

**Comment by yannickdeturck** [comment]
> Wait a moment @yannickdeturck, I have to do some CSS updates to make sure the badge is centered.

Sure thing, awaiting your "go".

**Comment by gurtjun** [comment]
Go 👌

**Pull request merged**
